const { chromium } = require('playwright');
const http = require('http');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = __dirname;
const routes = ['index.html','pages/forgiato.html','pages/custom-wheels.html','pages/factory-wheels.html','pages/new-tires.html','pages/auto-repair.html','pages/finance.html','pages/request-for-quote.html','pages/find-my-wheel-form.html','pages/quotes-history.html','pages/join-our-team.html','pages/privacy.html','pages/shop.html','pages/journal.html'];
const mime={'.html':'text/html; charset=utf-8','.webp':'image/webp','.js':'text/javascript','.yml':'text/plain'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/' )p='/index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('not found')}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});
(async()=>{const report={routes:{},desktop:{},mobile:{},external:{},assets:{},failures:[]};
for(const route of routes){const src=fs.readFileSync(path.join(root,route),'utf8');for(const m of src.matchAll(/<script(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g)){try{new vm.Script(m[1])}catch(e){report.failures.push(`${route}: JS syntax ${e.message}`)}}}
await new Promise(r=>server.listen(8910,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
for(const mode of [{name:'desktop',viewport:{width:1440,height:1000}},{name:'mobile',viewport:{width:390,height:844}}]){const context=await browser.newContext({viewport:mode.viewport});for(const route of routes){const page=await context.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(`http://127.0.0.1:8910/${route}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(300);const metrics=await page.evaluate(()=>({title:document.title,h1:document.querySelector('h1')?.innerText||'',overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,reveals:[...document.querySelectorAll('.reveal')].every(x=>getComputedStyle(x).opacity!=='0'),footer:!!document.querySelector('footer')}));const result={status:response?.status(),...metrics,errors};report[mode.name][route]=result;if(result.status!==200||result.overflow>2||!result.h1||!result.footer||errors.length)report.failures.push(`${mode.name} ${route}: ${JSON.stringify(result)}`);
if(mode.name==='mobile'){const menu=page.locator('.hamburger,.menu').first();if(await menu.count()){await menu.click();const open=await page.locator('.mobile-nav.active,.mobile.open').count();if(!open)report.failures.push(`${route}: mobile menu failed`);await page.keyboard.press('Escape');if(await page.locator('.mobile-nav.active,.mobile.open').count())report.failures.push(`${route}: Escape failed`)}}
if(route.includes('request-for-quote')||route.includes('find-my-wheel-form')||route.includes('join-our-team')){const form=page.locator('form').first();if(await form.count()){for(const input of await form.locator('input[required],textarea[required]').all()){const type=await input.getAttribute('type');await input.fill(type==='email'?'qa@example.com':type==='tel'?'3135551212':'QA Test')}await form.locator('button[type=submit]').click();if(!await page.locator('#form-result.show').count())report.failures.push(`${route}: form result failed`)}}
if(route==='index.html'&&mode.name==='desktop')await page.screenshot({path:path.join(root,'qa-home-desktop.png'),fullPage:true});if(route==='index.html'&&mode.name==='mobile')await page.screenshot({path:path.join(root,'qa-home-mobile.png'),fullPage:true});if(route==='pages/forgiato.html'&&mode.name==='desktop')await page.screenshot({path:path.join(root,'qa-forgiato-desktop.png'),fullPage:true});if(route==='pages/request-for-quote.html'&&mode.name==='mobile')await page.screenshot({path:path.join(root,'qa-quote-mobile.png'),fullPage:true});await page.close()}await context.close()}
const ctx=await browser.newContext({viewport:{width:1280,height:900}}),p=await ctx.newPage();await p.goto('http://127.0.0.1:8910/index.html',{waitUntil:'domcontentloaded'});await p.locator('.map-frame').scrollIntoViewIfNeeded();await p.waitForTimeout(3500);const map=await p.locator('iframe[title*="Bazzi Tires"]').getAttribute('src');const mapBox=await p.locator('.map-frame').boundingBox();const frameUrls=p.frames().map(f=>f.url());report.map={src:map,visible:!!mapBox&&mapBox.width>500&&mapBox.height>300,frameLoaded:frameUrls.some(x=>/google\.(com|ca)\/maps|maps\.google\./.test(x)),frameUrls};if(!report.map.visible||!report.map.frameLoaded||!map.includes('8001+Schaefer'))report.failures.push(`map: ${JSON.stringify(report.map)}`);await p.locator('#visit').screenshot({path:path.join(root,'qa-map-footer-desktop.png')});await p.goto('http://127.0.0.1:8910/pages/forgiato.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1600);await p.locator('main').screenshot({path:path.join(root,'qa-forgiato-content.png')});await ctx.close();
for(const asset of fs.readdirSync(path.join(root,'assets'))){const r=await fetch(`http://127.0.0.1:8910/assets/${asset}`);report.assets[asset]=r.status;if(r.status!==200)report.failures.push(`asset ${asset}: ${r.status}`)}
const external=new Set();for(const route of routes){const src=fs.readFileSync(path.join(root,route),'utf8');for(const m of src.matchAll(/<a[^>]+href="(https?:[^"#]+)"/g))external.add(m[1].replaceAll('&amp;','&'))}for(const url of external){try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0'},signal:AbortSignal.timeout(20000)});report.external[url]={status:r.status,final:r.url};if(r.status>=400)report.failures.push(`external ${url}: ${r.status}`)}catch(e){report.external[url]={error:e.message};report.failures.push(`external ${url}: ${e.message}`)}}
await browser.close();server.closeAllConnections?.();server.close();fs.writeFileSync(path.join(root,'qa-v8-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({routes:routes.length,desktop:Object.keys(report.desktop).length,mobile:Object.keys(report.mobile).length,map:report.map,assets:report.assets,external:report.external,failures:report.failures},null,2));if(report.failures.length)process.exit(1)})().catch(e=>{console.error(e);server.close();process.exit(1)});

